### ISSUE TITLE
Pin required

### ISSUE THREAD

**Issue by joseluislucio** [J3Patel/linkedin-learning-video-downloader#11]
Trying to do my second course download I get the following error:

2020-06-14 13:48:07,881 root         INFO     [*] Login step 1 - Done
2020-06-14 13:48:07,881 root         INFO     [*] Login step 2 - Logging In...
2020-06-14 13:48:08,518 root         INFO     [*] Login step 2 - Done
2020-06-14 13:48:08,518 root         INFO     [*] -------------Done-------------
2020-06-14 13:48:08,518 root         INFO     [*] -------------Fetching Course-------------
Traceback (most recent call last):
  File "linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 213, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 111, in fetch_course
    data = await resp.json()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=videos&addParagraphsToTranscript=true&courseSlug=windows-management-with-system-center-configuration-manager&q=slugs')

And I also received an email with a pin number to login. Is there any way to send the pin received?

Regards

**Comment by J3Patel** [comment]
@joseluislucio this mimetype issue is fixed now, have you added 2 factor authentication in your linkedin account?
