### ISSUE TITLE
KeyError: 'Url'

### ISSUE THREAD

**Issue by rynygskt** [J3Patel/linkedin-learning-video-downloader#13]
i have an error like this:

Traceback (most recent call last):
  File "linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "E:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 616
, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 213, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 116, in fetch_course
    await fetch_chapters(course)
  File "linkedin_learning.py", line 128, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for
 chapter in course.chapters))
  File "linkedin_learning.py", line 162, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['Url']['progressiveUrl']
KeyError: 'Url'

**Comment by mdelapenya** [comment]
This seems solved in this project: https://github.com/liranbg/linkedin-learning-downloader/blob/master/linkedin_learning.py

**Comment by J3Patel** [comment]
@rynygskt Fixed, Thanks for reporting!
