### ISSUE TITLE
KeyError: 'transcript'

### ISSUE THREAD

**Issue by Naiki92** [J3Patel/linkedin-learning-video-downloader#16]
I get this error. Maybe a problem with German transcript?

Traceback (most recent call last):
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 246, in <module>
    loop.run_until_complete(process())
  File "C:\Users\Marcel\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 231, in process
    await fetch_collections()
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 106, in fetch_collections
    return await asyncio.gather(*map(fetch_collection, COLLECTIONS))
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 120, in fetch_collection
    await fetch_course(course['com.linkedin.learning.api.ListedCourse']['slug'])
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 134, in fetch_course
    await fetch_chapters(course)
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 146, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "C:\Users\Marcel\Downloads\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 181, in fetch_video
    subtitles = data['elements'][0]['selectedVideo']['transcript']['lines']
KeyError: 'transcript'

**Comment by J3Patel** [comment]
@Naiki92 Fixed, Please take new pull, Thanks for reporting
