### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by RomainLpt31** [J3Patel/linkedin-learning-video-downloader#19]
First of all, thanks a lot for this project!

But I have a problem when i want to download some courses. I use Debian 10.7 buster.

Here's the following error I always have:

`Traceback (most recent call last):
  File "linkedin_learning.py", line 254, in <module>
    loop.run_until_complete(process())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 242, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 130, in fetch_course
    data = await resp.json()
  File "/home/*****/.local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=videos&addParagraphsToTranscript=true&courseSlug=*****&q=slugs')
`

I have the same problem on my other Windows 10 computer with python 3.6

**Comment by neomrx** [comment]
Hi,

same problem on windows 10 with Python 3.9
Traceback (most recent call last):
  File "C:\Linkedin\linkedin_learning.py", line 254, in <module>
    loop.run_until_complete(process())
  File "C:\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Linkedin\linkedin_learning.py", line 242, in process
    await fetch_courses()
  File "C:\Linkedin\linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "C:\Linkedin\linkedin_learning.py", line 130, in fetch_course
    data = await resp.json()
  File "C:\Python\lib\site-packages\aiohttp\client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=videos&addParagraphsToTranscript=true&courseSlug=********&q=slugs')

**Comment by J3Patel** [comment]
@neomrx @neomrx send me your config file

**Comment by neomrx** [comment]
> 
> 
> @neomrx @neomrx send me your config file

Thanks in advance

[linkedin_learning.zip](https://github.com/J3Patel/linkedin-learning-video-downloader/files/5815041/linkedin_learning.zip)

**Comment by neomrx** [comment]
Hi,

now, it's impossible to download corrctely the video file, for every cours i recive this message "[~] Done fetching course" but file size still about 71Ko.

need your help.

**Comment by kengy88** [comment]
No issue downloading.
Make sure the config is edited correctly.

Edit the below path if you are using Win 10.
BASE_DOWNLOAD_PATH = **os.path.expanduser('~/Downloads')**

**Comment by elderaranda** [comment]
This is a great project! By the way, would you be able to modify the code so that it downloads one file at a time? I think the download fails after waiting for too long to complete the writing process.
