### ISSUE TITLE
asyncio error in both Mac and Windows

### ISSUE THREAD

**Issue by aelharda** [J3Patel/linkedin-learning-video-downloader#2]
2019-09-17 13:40:28,289 asyncio      DEBUG    Using selector: SelectSelector
2019-09-17 13:40:28,293 root         INFO     [*] -------------Login-------------
2019-09-17 13:40:28,293 root         INFO     xxxxxxxx@xx.com
2019-09-17 13:40:28,295 root         INFO     xxxxxxxxx
2019-09-17 13:40:28,295 root         INFO     [*] Login step 1 - Getting CSRF token...
2019-09-17 13:40:28,709 root         DEBUG    [*] CSRF: 9fe47bf5-xxxx-4e53-xxxx-b44710de95e1
2019-09-17 13:40:28,709 root         INFO     [*] Login step 1 - Done
2019-09-17 13:40:28,711 root         INFO     [*] Login step 2 - Logging In...
2019-09-17 13:40:29,314 root         INFO     [*] Login step 2 - Done
2019-09-17 13:40:29,315 root         INFO     [*] -------------Done-------------
2019-09-17 13:40:29,316 root         INFO     [*] -------------Fetching Course-------------
2019-09-17 13:40:29,817 root         INFO     [*] Access to Learning Autodesk Inventor is DENIED
2019-09-17 13:40:29,827 asyncio      ERROR    Unclosed connection
client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=False, proxy=None, proxy_auth=None, proxy_headers_hash=-1919483482)>
2019-09-17 13:40:29,829 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 6 Video no. 3
2019-09-17 13:40:29,831 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 2 Video no. 3
2019-09-17 13:40:29,833 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 4
2019-09-17 13:40:29,836 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 5
2019-09-17 13:40:29,838 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 1
2019-09-17 13:40:29,840 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 5
2019-09-17 13:40:29,842 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 6 Video no. 4
2019-09-17 13:40:29,842 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 2
2019-09-17 13:40:29,843 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 1
2019-09-17 13:40:29,846 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 6
2019-09-17 13:40:29,849 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 7
2019-09-17 13:40:29,849 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 7
2019-09-17 13:40:29,852 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 4
2019-09-17 13:40:29,855 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 5
2019-09-17 13:40:29,857 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 1
2019-09-17 13:40:29,860 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 3
2019-09-17 13:40:29,862 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 6
2019-09-17 13:40:29,864 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 2
2019-09-17 13:40:29,866 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 3 Video no. 1
2019-09-17 13:40:29,866 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 2
2019-09-17 13:40:29,871 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 3
2019-09-17 13:40:29,872 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 4
2019-09-17 13:40:29,884 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 1 Video no. 2
2019-09-17 13:40:29,887 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 1 Video no. 1
2019-09-17 13:40:29,888 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 2 Video no. 1
2019-09-17 13:40:29,890 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 2 Video no. 2
2019-09-17 13:40:29,893 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 6 Video no. 5
2019-09-17 13:40:29,896 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 8 Video no. 1
2019-09-17 13:40:29,898 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 6 Video no. 1
2019-09-17 13:40:29,900 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 6 Video no. 2
2019-09-17 13:40:29,902 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 8
2019-09-17 13:40:29,904 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 6
2019-09-17 13:40:29,908 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 7
2019-09-17 13:40:29,909 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 4
2019-09-17 13:40:29,910 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 6
2019-09-17 13:40:29,911 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 5
2019-09-17 13:40:29,913 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 5 Video no. 7
2019-09-17 13:40:29,914 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 2
2019-09-17 13:40:29,916 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 4 Video no. 3
2019-09-17 13:40:29,919 root         INFO     [~] Fetching course 'Learning Autodesk Inventor' Chapter no. 7 Video no. 3
Traceback (most recent call last):
  File ".\linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File ".\linkedin_learning.py", line 213, in process
    await fetch_courses()
  File ".\linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File ".\linkedin_learning.py", line 116, in fetch_course
    await fetch_chapters(course)
  File ".\linkedin_learning.py", line 128, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File ".\linkedin_learning.py", line 162, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']
KeyError: 'url'

**Comment by J3Patel** [comment]
@aelharda  this is issue is fixed

**Comment by Husnain08** [comment]
@J3Patel  I am getting this error again and again. I cloned this repository half an hour ago and I am getting the error below

    headers=self.headers,
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.linkedin.com/learning-api/detailedCourses??fields=videos&addParagraphsToTranscript=true&courseSlug=inclusive-tech-conducting-humane-code-review&q=slugs')
2021-01-14 12:33:47,539 asyncio      ERROR    Unclosed connection
client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=False, proxy=None, proxy_auth=None, proxy_headers_hash=309043347007192497)>
