### ISSUE TITLE
anyone help me solve this issue

### ISSUE THREAD

**Issue by Moinaansari** [J3Patel/linkedin-learning-video-downloader#25]
Traceback (most recent call last):
  File "C:\Python\Linkedin\linkedin-learning-downloader-master\lld.py", line 12, in <module>
    from config import USERNAME, PASSWORD, COURSES, PROXY, BASE_DOWNLOAD_PATH
  File "C:\Python\Linkedin\linkedin-learning-downloader-master\config.py", line 5
    COURSES = [Cisco Certified CyberOps Associate Cert Prep: 1 Security Concepts]
                     ^
SyntaxError: invalid syntax

**Comment by NL-TCH** [comment]
set the course between quotes like:
COURSES = ['Cisco Certified CyberOps Associate Cert Prep: 1 Security Concepts']
