### ISSUE TITLE
Empty Folders

### ISSUE THREAD

**Issue by shbmfu003** [J3Patel/linkedin-learning-video-downloader#7]
Traceback (most recent call last):
  File "M:\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 225, in <module>
    loop.run_until_complete(process())
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "M:\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 213, in process
    await fetch_courses()
  File "M:\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "M:\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 116, in fetch_course
    await fetch_chapters(course)
  File "M:\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 128, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "M:\linkedin-learning-video-downloader-master\linkedin-learning-video-downloader-master\linkedin_learning.py", line 162, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']
KeyError: 'url'

**Comment by atj393** [comment]
I am also facing the same issue!

**Comment by J3Patel** [comment]
@atj393 @shbmfu003  can you try again now, if still getting same issue please add config file here.
Thanks
